/** Mac Avenir Next + PingFang SC. Windows Bahnschrift + DengXian, then YaHei. */
const glassSans = '"Avenir Next",Bahnschrift,"Segoe UI","PingFang SC",DengXian,"Microsoft YaHei UI",sans-serif'

/** Card rules for the panel sheet and every app sheet. Not scoped to the panel host. */
export const appCardCss = [
  '.mma-slot{display:grid;min-width:0;}',
  `.mma-glass{display:grid;width:100%;height:100%;min-height:100%;box-sizing:border-box;border-radius:24px;border:1px solid color-mix(in oklch,var(--foreground) 8%,transparent);background:color-mix(in oklch,var(--card) 62%,transparent);padding:18px;text-align:left;font-family:${glassSans};backdrop-filter:blur(16px);transition:transform .4s cubic-bezier(.23,1,.32,1),background-color .4s,box-shadow .4s;}`,
  '.mma-glass-body{display:flex;width:100%;height:100%;min-height:100%;flex-direction:column;justify-content:flex-start;gap:12px;}',
  '.mma-feature .mma-glass{padding:24px;}',
  '.mma-feature .mma-glass-body{justify-content:space-between;gap:15px;}',
  '.mma-glass-name{margin:0;font-size:18px;font-weight:700;letter-spacing:-.02em;line-height:1.25;}',
  '.mma-feature .mma-glass-name{font-size:24px;}',
  '.mma-glass-copy{margin:6px 0 0;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden;font-size:12px;font-weight:400;line-height:1.45;color:var(--muted-foreground);}',
  '.mma-feature .mma-glass-copy{margin-top:8px;font-size:14px;line-height:1.625;}',
  'button[data-card="stamp"] .mma-copy,button[data-card="etch"] .mma-copy,button[data-card="pulse"] .mma-copy,button[data-card="hero"] .mma-copy{min-height:2.75em;}',
  // No background on hover. A card that hosts something — a running app in a workbench slot, chips
  // inside a preview — is hovered whenever its content is, and swapping the card's background
  // paints a white one behind content that was designed against the card's own tint.
  '.mma-glass:hover{transform:translateY(-4px);box-shadow:0 20px 40px -16px color-mix(in oklch,var(--foreground) 16%,transparent);}',
  '.mma-feature{grid-column:span 2;}',
  '@container (max-width:680px){.mma-feature{grid-column:span 1;}}',
  '.mma-mark{font-size:30px;font-weight:800;letter-spacing:-1px;line-height:1;background:linear-gradient(to bottom right,hsl(var(--h) 48% 46%),hsl(var(--h) 40% 38% / .35));-webkit-background-clip:text;background-clip:text;color:transparent;}',
  '.mma-feature .mma-mark{font-size:48px;letter-spacing:-2px;}',
  '.mma-tag{border-radius:6px;background:color-mix(in oklch,var(--foreground) 6%,transparent);padding:2px 8px;font-size:10px;font-weight:700;letter-spacing:.04em;color:var(--muted-foreground);}',
  '[data-mode="dark"] .mma-glass{background:color-mix(in oklch,var(--foreground) 4%,transparent);border-color:color-mix(in oklch,var(--foreground) 12%,transparent);}',
  '[data-mode="dark"] .mma-mark{background:linear-gradient(to bottom right,hsl(var(--h) 42% 74%),hsl(var(--h) 30% 52% / .28));-webkit-background-clip:text;background-clip:text;}',
  `#mma-host[data-card="glass"] .mma-library{font-family:${glassSans};}`,
  'button[data-app-id]{transition:border-color .16s ease,box-shadow .16s ease,transform .16s ease,background-color .22s ease;}',
  '@keyframes mma-hero-breath{0%,100%{transform:translate(-50%,-50%) scale(1);filter:blur(10px) brightness(1)}50%{transform:translate(-50%,-50%) scale(.86);filter:blur(12px) brightness(.75)}}',
  'button[data-app-id][data-card="hero"] .hero-chip{position:relative;z-index:1;display:inline-flex;align-items:center;justify-content:center;min-width:2.15rem;height:1.45rem;padding:0 .42rem;border-radius:.35rem;background:hsl(var(--h) 62% 46%);color:#fff;font-size:11px;font-weight:700;letter-spacing:.06em;line-height:1;}',
  '[data-mode="dark"] button[data-app-id][data-card="hero"] .hero-chip{background:#fff;color:hsl(var(--h) 58% 36%);}',
  'button[data-app-id][data-card="hero"] .hero-mist{position:absolute;border-radius:50%;pointer-events:none;opacity:0;filter:blur(10px);transform:translate(-50%,-50%) scale(.5);transition:opacity 1.2s ease,transform 1.2s ease;}',
  'button[data-app-id][data-card="hero"] .hero-mist-a{left:74%;top:30%;width:84px;height:84px;background:radial-gradient(circle,hsl(var(--h) 72% 56% / .85),transparent 70%);}',
  'button[data-app-id][data-card="hero"] .hero-mist-b{left:30%;top:74%;width:56px;height:56px;background:radial-gradient(circle,hsl(var(--h) 64% 54% / .7),transparent 70%);}',
  'button[data-app-id][data-card="hero"] .hero-mist-c{left:26%;top:28%;width:48px;height:48px;background:radial-gradient(circle,hsl(var(--h) 56% 58% / .55),transparent 72%);}',
  'button[data-app-id][data-card="hero"]:hover{background:var(--card);border-color:hsl(var(--h) 58% 46% / .72);box-shadow:0 0 8px 0 hsl(var(--h) 62% 48% / .55);transform:translateY(-1px);}',
  'button[data-app-id][data-card="hero"]:hover .hero-mist{opacity:.7;transform:translate(-50%,-50%) scale(1);}',
  '[data-mode="dark"] button[data-app-id][data-card="hero"] .hero-mist-a{background:radial-gradient(circle,hsl(var(--h) 58% 72% / .8),transparent 70%);}',
  '[data-mode="dark"] button[data-app-id][data-card="hero"] .hero-mist-b{background:radial-gradient(circle,hsl(var(--h) 48% 70% / .65),transparent 70%);}',
  '[data-mode="dark"] button[data-app-id][data-card="hero"] .hero-mist-c{background:radial-gradient(circle,hsl(var(--h) 42% 74% / .5),transparent 72%);}',
  '[data-mode="dark"] button[data-app-id][data-card="hero"]:hover{border-color:hsl(var(--h) 40% 62% / .45);box-shadow:0 0 8px 0 hsl(var(--h) 50% 68% / .28);}',
  '[data-mode="dark"] button[data-app-id][data-card="hero"]:hover .hero-mist{opacity:.62;}',
  'button[data-app-id][data-card="hero"]:hover .hero-mist-a{animation:mma-hero-breath 4.2s ease-in-out 1.2s infinite;}',
  'button[data-app-id][data-card="hero"]:hover .hero-mist-b{opacity:.55;animation:mma-hero-breath 5.4s ease-in-out 1.2s infinite;}',
  'button[data-app-id][data-card="hero"]:hover .hero-mist-c{opacity:.45;animation:mma-hero-breath 6.6s ease-in-out 1.2s infinite;}',
  'button[data-app-id][data-card="etch"]{border-width:2px;border-style:solid;border-top-color:var(--card);border-left-color:var(--card);border-right-color:hsl(var(--h) 65% 45%);border-bottom-color:hsl(var(--h) 65% 45%);transition:border-color .9s ease,box-shadow .9s ease,background-color .22s ease;}',
  'button[data-app-id][data-card="etch"] .etch-line{transition:opacity .55s ease;}',
  'button[data-app-id][data-card="etch"] .etch-fill{opacity:0;transition:opacity .55s ease;}',
  'button[data-app-id][data-card="etch"]:hover .etch-line{opacity:0;}',
  'button[data-app-id][data-card="etch"]:hover{border-color:hsl(var(--h) 65% 45%);background:var(--card);transform:none;box-shadow:hsl(var(--h) 70% 50% / .40) 5px 5px,hsl(var(--h) 70% 50% / .28) 10px 10px,hsl(var(--h) 70% 50% / .16) 15px 15px;}',
  'button[data-app-id][data-card="etch"]:hover .etch-fill{opacity:1;}',
  'button[data-app-id][data-card="stamp"]:hover{background:linear-gradient(hsl(var(--h) 30% 55% / .07),hsl(var(--h) 30% 55% / .07)),var(--card);border-color:var(--foreground);box-shadow:0 8px 22px var(--shadow);transform:translateY(-1px);}',
  'button[data-app-id][data-card="stamp"]:hover [data-monogram="stamp"]{background:var(--foreground);color:var(--card);transform:scale(1.05);}',
  '@keyframes mma-list-spin{to{transform:rotate(360deg)}}',
  'button[data-app-id][data-card="list"] .list-backlight{position:absolute;top:0;right:0;z-index:0;width:46%;height:100%;background:linear-gradient(to left,hsl(var(--h) 58% 58% / .52),hsl(var(--h) 46% 56% / .2) 55%,transparent);opacity:0;pointer-events:none;transition:opacity .6s ease;}',
  'button[data-app-id][data-card="list"] .list-wash{position:absolute;inset:4px;z-index:1;border-radius:12px 64px 22px 12px;background:hsl(var(--h) 16% 46% / .06);backdrop-filter:blur(10px);pointer-events:none;transition:background-color .28s ease;}',
  'button[data-app-id][data-card="list"] .list-orb{position:absolute;top:50%;right:28px;width:76px;height:76px;margin-top:-38px;border-radius:50%;background:conic-gradient(from 90deg,transparent 0%,hsl(var(--h) 42% 58% / 0) 20%,hsl(var(--h) 48% 50% / .55) 50%,transparent 76%);filter:blur(8px);animation:mma-list-spin 16s linear infinite;pointer-events:none;}',
  '@keyframes mma-list-nudge{0%{transform:translateX(0)}45%{transform:translateX(4px)}100%{transform:translateX(0)}}',
  '@keyframes mma-list-mark{0%{letter-spacing:.04em;opacity:.8}40%{letter-spacing:.18em;opacity:1}100%{letter-spacing:.08em;opacity:1}}',
  'button[data-app-id][data-card="list"] .list-mark{display:block;font-size:13px;font-weight:700;line-height:1;letter-spacing:.04em;white-space:nowrap;color:var(--foreground);opacity:.8;}',
  'button[data-app-id][data-card="list"] .list-go svg{display:block;}',
  'button[data-app-id][data-card="list"]::after{content:"";position:absolute;inset:0;z-index:2;border-radius:inherit;padding:1px;background:linear-gradient(155deg,hsl(var(--h) 58% 46% / .9),hsl(var(--h) 42% 52% / .5) 40%,transparent 72%);-webkit-mask:linear-gradient(#000 0 0) content-box,linear-gradient(#000 0 0);-webkit-mask-composite:xor;mask-composite:exclude;opacity:0;pointer-events:none;transition:opacity .28s ease;}',
  'button[data-app-id][data-card="list"]:hover{border-color:transparent;background:var(--card);}',
  'button[data-app-id][data-card="list"]:hover::after{opacity:1;}',
  'button[data-app-id][data-card="list"]:hover .list-backlight{opacity:1;}',
  'button[data-app-id][data-card="list"]:hover .list-wash{background:hsl(var(--h) 28% 48% / .12);}',
  '[data-mode="dark"] button[data-app-id][data-card="list"] .list-backlight{background:linear-gradient(to left,hsl(var(--h) 28% 64% / .32),transparent 70%);}',
  '[data-mode="dark"] button[data-app-id][data-card="list"] .list-orb{background:conic-gradient(from 90deg,transparent 0%,hsl(var(--h) 22% 62% / 0) 20%,hsl(var(--h) 18% 55% / .42) 50%,transparent 76%);}',
  '[data-mode="dark"] button[data-app-id][data-card="list"]::after{background:linear-gradient(155deg,hsl(0 0% 100% / .9),hsl(var(--h) 35% 62% / .4) 36%,transparent 70%);}',
  '[data-mode="dark"] button[data-app-id][data-card="list"]:hover .list-wash{background:hsl(var(--h) 16% 46% / .1);}',
  'button[data-app-id][data-card="list"]:hover .list-mark{color:hsl(var(--h) 42% 36%);animation:mma-list-mark .55s ease forwards;}',
  '[data-mode="dark"] button[data-app-id][data-card="list"]:hover .list-mark{color:hsl(var(--h) 48% 74%);}',
  'button[data-app-id][data-card="list"]:hover .list-go{background:hsl(var(--h) 42% 48% / .2);}',
  'button[data-app-id][data-card="list"]:hover .list-go svg{animation:mma-list-nudge .45s ease;}',
  '@keyframes mma-pulse-dot{0%,100%{background:hsl(var(--h) 60% 52% / 0)}50%{background:hsl(var(--h) 75% 48%)}}',
  '@keyframes mma-pulse-glow{0%,100%{opacity:0}50%{opacity:1}}',
  'button[data-app-id][data-card="pulse"]{border:none;background:linear-gradient(hsl(0 0% 100% / .35),hsl(0 0% 0% / .03)),var(--card);box-shadow:1px 1px 2px -1px #fff inset,0 2px 1px #00000010,0 8px 8px #00000012;transition:transform .25s cubic-bezier(.25,1.5,.5,1),filter .3s ease;}',
  'button[data-app-id][data-card="pulse"] .pulse-mark{color:hsl(var(--h) 48% 38%);}',
  '[data-mode="dark"] button[data-app-id][data-card="pulse"]{background:linear-gradient(hsl(var(--h) 22% 58% / .1),transparent 42%),var(--card);box-shadow:inset 0 1px 0 hsl(0 0% 100% / .07),0 10px 18px hsl(0 0% 0% / .4);}',
  '[data-mode="dark"] button[data-app-id][data-card="pulse"] .pulse-mark{color:hsl(var(--h) 40% 74%);}',
  'button[data-app-id][data-card="pulse"] .pulse-dot{position:absolute;top:16px;right:14px;width:8px;height:8px;border-radius:50%;border:1px solid hsl(var(--h) 40% 55% / .55);animation:mma-pulse-dot 1.2s ease-in-out infinite;}',
  'button[data-app-id][data-card="pulse"] .pulse-dot::after{content:"";position:absolute;inset:-7px;border-radius:inherit;box-shadow:0 0 10px 2px hsl(var(--h) 80% 55% / .35),0 0 18px 6px hsl(var(--h) 80% 60% / .2);animation:mma-pulse-glow 1.2s ease-in-out infinite;}',
  'button[data-app-id][data-card="pulse"]:hover{transform:translateY(-2px);filter:drop-shadow(6px 0 6px hsl(var(--h) 70% 55% / .45));}',
  'button[data-app-id][data-card="pulse"]:hover .pulse-dot{animation:none;background:hsl(var(--h) 75% 48%);}',
  'button[data-app-id][data-card="pulse"]:hover .pulse-dot::after{animation:none;opacity:1;}',
].join('\n')
