/** Locales the panel chrome speaks. No third locale. */
export const panelLocales = ['en', 'zh-CN'] as const

export type PanelLocale = (typeof panelLocales)[number]

export type PanelLabelMode = 'development' | 'production'

const en = {
  'host-unreachable': 'Host is unreachable',
  'gallery-empty': 'No apps yet',
  'gallery-title': 'Library',
  'gallery-count': '{n} apps',
  'status-ready': 'Host ready',
  'card-style': 'Card style',
  'card-hero': 'Glow',
  'card-stamp': 'Stamp',
  'card-etch': 'Cutout',
  'card-pulse': 'Firefly',
  'card-list': 'List',
  'card-glass': 'Glass',
  'search-placeholder': 'Search mini apps',
  'search-empty': 'No matching apps',
  'list-failed': 'The app list failed',
  'trash-failed': 'Trash failed to load',
  'reload-failed': 'Reload failed',
  'probe-ok': 'Healthy',
  'probe-failed': 'Probe failed',
  'history-empty': 'No history yet',
  'history-failed': 'History failed to load',
  'delete-confirm': 'Delete this app?',
  'delete-failed': 'Delete failed',
  'unsaved-confirm': 'Discard unsaved changes?',
  'port-invalid': 'Port must be from 1024 to 65535',
  'save-failed': 'Save failed',
  'update-failed': 'Update check failed',
  'storage-failed': 'Storage failed to load',
  'storage-size-notice': 'The storage file is large ({table}). Ask an agent to help split the data.',
  'restore-storage': 'Restore storage',
  'restore-storage-confirm': 'Restore the last storage backup? This replaces the live database.',
  'theme-save-failed': 'Theme pin failed to save',
  search: 'Search',
  open: 'Open',
  'open-failed': 'Open failed',
  'frame-pending': 'Opening…',
  'close-tab': 'Close',
  gallery: 'All',
  delete: 'Delete',
  cancel: 'Cancel',
  confirm: 'Confirm',
  restore: 'Restore',
  language: 'Language',
  port: 'Host port',
  'port-help': 'Local HTTP port for the host: panel, app iframes, APIs, and MCP authoring. Changing it needs a host restart and an MCP connection update.',
  'port-edit': 'Edit host port',
  'port-lock': 'Lock host port',
  'port-open-panel': 'Open in browser',
  'port-panel-url': 'Panel',
  'port-mcp-url': 'MCP authoring',
  save: 'Save',
  saving: 'Saving…',
  saved: 'Saved',
  probe: 'Probe',
  'restart-required': 'The host must restart before the new port or runtime is used.',
  'restart-mcp-hint': 'After restart, open Agent settings and update the MCP authoring connection so assistants use the new port.',
  'restart-runtime-hint': 'Mini-apps keep the previous runtime until the host restarts.',
  'restart-runtime-pending': 'Save, then restart the host. Apps still use the previous runtime until then.',
  'restart-host': 'Restart host',
  'restart-wait': 'Restarting the host…',
  'restart-failed': 'The host did not restart.',
  dismiss: 'Dismiss',
  'follow-host': 'Follow host',
  'app-file': 'App file',
  'clear-pin': 'Clear',
  refresh: 'Refresh',
  reload: 'Reload',
  'settings-close': 'Close settings',
  'section-appearance': 'Appearance',
  'section-workbench': 'Workbench',
  'desk-switch': 'Workbench',
  'workbench-builtin': 'Library',
  'workbench-mark': 'Workbench',
  'set-default-workbench': 'Set as home',
  'current-default-workbench': 'Current home',
  'clear-default-workbench': 'Clear home',
  'open-workbench-tab': 'Open as tab',
  'open-workbench-tab-now': 'Custom home',
  'open-workbench-tab-more': 'More in a tab',
  'open-workbench-tab-hint': 'Open this workbench in a tab for storage, history, and theme',
  'section-network': 'Network',
  'section-runtime': 'Runtime',
  'section-model': 'Mini-app model',
  'section-agent': 'Agent',
  'section-about': 'About',
  'section-mcp': 'MCP',
  'section-credentials': 'Credentials',
  'credentials-empty': 'No credentials yet. Add one and a server can name it instead of holding the secret.',
  'credentials-add': 'Add credential',
  'credentials-new': 'New credential',
  'credentials-edit': 'Edit credential',
  'credentials-name': 'Name',
  'credentials-name-hint': 'e.g. github',
  'credentials-description': 'Description',
  'credentials-desc-hint': 'What this account is for',
  'credentials-secret': 'Secret',
  'credentials-secret-hint': 'Paste the token',
  'credentials-replace-hint': 'Leave the secret empty to keep the stored one.',
  'credentials-need-name': 'Give the credential a name first.',
  'credentials-need-secret': 'A new credential needs a secret.',
  'credentials-save': 'Save',
  'credentials-saved': 'Saved on this machine only.',
  'credentials-saved-description': 'Description saved. The stored secret is unchanged.',
  'credentials-read-only': 'This store cannot be written from here.',
  'credentials-load-failed': 'Credentials could not be read.',
  'credentials-save-failed': 'The credential was not saved.',
  'credentials-delete-confirm': 'Delete this credential? Servers that name it stop starting.',
  'credentials-reference': 'A server references this as {reference}',
  'mcp-reference-hint': 'A value may be ${env:NAME} or ${credential:NAME}',
  'mcp-unstarted': 'Not started',
  'mcp-unresolved-hint': 'A server below is not running because a value names something missing. Add it in Credentials, then restart the host.',
  'mcp-add': 'Add server',
  'mcp-new': 'New server',
  'mcp-edit': 'Edit server',
  'mcp-check': 'Check connection',
  'mcp-check-ok': 'Connected. {n} tools.',
  'mcp-need-name': 'Give the server a name first.',
  'mcp-save': 'Add server',
  'mcp-empty': 'No servers yet. Add one to give apps external tools.',
  'mcp-transport': 'Transport',
  'mcp-stdio': 'Local command',
  'mcp-sse': 'SSE',
  'mcp-http': 'HTTP',
  'mcp-name': 'Name',
  'mcp-description': 'Description',
  'mcp-command': 'Command',
  'mcp-args': 'Arguments',
  'mcp-url': 'URL',
  'mcp-env': 'Environment',
  'mcp-tools': 'Tools',
  'mcp-connected': 'Connected',
  'mcp-offline': 'Not connected',
  'mcp-saved': 'Saved. Apps use this file the next time the host starts.',
  'mcp-name-hint': 'e.g. filesystem',
  'mcp-desc-hint': 'What this server does',
  'mcp-command-hint': 'e.g. npx',
  'mcp-args-hint': '-y @mcp/server',
  'mcp-url-hint': 'https://example.com/mcp',
  'mcp-env-hint': 'KEY=value, one per line',
  'mcp-headers': 'Headers',
  'mcp-headers-hint': 'Authorization=Bearer token',
  'mcp-authoring': 'Install MCP authoring tools',
  'mcp-authoring-help': 'Lets Cursor, Pi, and similar assistants create and edit mini-apps on this machine.',
  'mcp-authoring-generate': 'Generate connection',
  'mcp-authoring-install': 'Install connection',
  'mcp-authoring-update-install': 'Update connection',
  'mcp-authoring-failed': 'The connection could not be installed.',
  'mcp-authoring-blurb': 'Create and edit mini-apps on this machine.',
  'agent-apps-help': 'Mini-apps use this model for chat and agents.',
  'agent-others': 'App authoring agents',
  'agent-others-help': 'Install the writing skill and tools on agents.',
  installing: 'Installing',
  'skill-help': 'Teaches the assistant how to write mini-apps. Choose where to install.',
  'skill-install': 'Install writing skill',
  'skill-installed': 'Installed',
  'skill-update': 'Update available',
  'skill-update-install': 'Update writing skill',
  'skill-version': 'Version {n}',
  'skill-reinstall': 'Reinstall',
  'skill-failed': 'The skill could not be installed.',
  'skill-missing-home': 'Not detected',
  'skill-open': 'Open',
  'skill-custom': 'Custom folder',
  'skill-custom-hint': 'e.g. ~/.agents/skills or project/.agents/skills',
  'skill-custom-format': 'The last folder must be named skills.',
  'skill-add-dir': 'Add',
  'mcp-copy': 'Copy',
  'mcp-copied': 'Copied',
  'mcp-paste': 'Paste',
  'mcp-from-pi': 'From Pi',
  'mcp-from-file': 'Choose file',
  'mcp-import': 'Import',
  'mcp-admit': 'Recognize',
  'mcp-import-none': 'No servers were found in that config.',
  'mcp-load-failed': 'The MCP file could not be read.',
  'mcp-running': 'Running',
  'mcp-stopped': 'Stopped',
  'mcp-more': '{n} more',
  'mcp-tool-empty': 'This tool has no description.',
  'mcp-pick': 'Choose servers to import',
  'model-empty': 'This runtime does not list models.',
  'runtime-missing': 'No runtime is registered.',
  'update-checking': 'Checking…',
  'update-ok': 'This version is current.',
  'update-available': 'A newer version is available.',
  'update-current': 'This version: {n}',
  'update-newest': 'Latest: {n}',
  'lang-zh': 'Chinese',
  'lang-en': 'English',
  'theme-system': 'System',
  'theme-light': 'Light',
  'theme-dark': 'Dark',
  'scope-global': 'Global',
  'scope-app': 'This app',
  'chip-system': 'System',
  'chip-custom': 'Custom',
  'chip-app': 'App',
  'follow-global': 'Follow global',
  trash: 'Trash',
  'close-panel': 'Close panel',
  appearance: 'Appearance',
  'theme-app-hint': 'Pin a palette for this app so it stays put when the host palette changes. Light and dark still follow the host.',
  palette: 'Palette',
  provider: 'Provider',
  model: 'Model',
  about: 'About',
  'product-name': 'Mohou',
  'product-meaning': 'Mohou is the small monkey once kept to grind ink. It is small, stays at hand, and serves one task.\nThis product is that set of tools. You bring the idea. The language model writes the implementation. Mohou supplies the brush, the ink, the paper, the inkstone, the library, and the shelf.',
  update: 'Check for updates',
  'update-install': 'Install update',
  'update-install-confirm': 'Install {n} and restart the host?',
  'update-installing': 'Installing the update. The host will restart.',
  'update-install-failed': 'The update could not be installed.',
  settings: 'Settings',
  history: 'History',
  storage: 'Storage',
  theme: 'Theme',
  'pane-close': 'Close',
  'history-pick': 'Select a commit to see what changed',
  'storage-empty-rows': 'This table has no rows',
  'storage-preview': 'Preview',
  'storage-raw': 'Raw',
} as const

const zhCN = {
  'host-unreachable': '无法连接宿主',
  'gallery-empty': '还没有应用',
  'gallery-title': '小程序库',
  'gallery-count': '共 {n} 个小程序',
  'status-ready': '系统运行正常',
  'card-style': '卡片样式',
  'card-hero': '光晕',
  'card-stamp': '印章',
  'card-etch': '剪影',
  'card-pulse': '萤火',
  'card-list': '列表',
  'card-glass': '玻璃',
  'search-placeholder': '搜索小程序',
  'search-empty': '没有匹配的应用',
  'list-failed': '应用列表加载失败',
  'trash-failed': '回收站加载失败',
  'reload-failed': '重新加载失败',
  'probe-ok': '正常',
  'probe-failed': '探测失败',
  'history-empty': '还没有历史',
  'history-failed': '历史加载失败',
  'delete-confirm': '删除这个应用？',
  'delete-failed': '删除失败',
  'unsaved-confirm': '放弃未保存的修改？',
  'port-invalid': '端口必须在 1024 到 65535 之间',
  'save-failed': '保存失败',
  'update-failed': '更新检查失败',
  'storage-failed': '存储加载失败',
  'storage-size-notice': '数据存储文件过大（{table}）。可让智能体帮助拆分数据。',
  'restore-storage': '恢复存储',
  'restore-storage-confirm': '还原上次的存储备份？当前数据库会被换掉。',
  'theme-save-failed': '主题固定失败',
  search: '搜索',
  open: '打开',
  'open-failed': '打开失败',
  'frame-pending': '正在打开…',
  'close-tab': '关闭',
  gallery: '全部',
  delete: '删除',
  cancel: '取消',
  confirm: '确认',
  restore: '还原',
  language: '语言',
  port: '宿主端口',
  'port-help': '本机 Host 的 HTTP 端口：面板、小程序、接口和 MCP 创作工具都走这个地址。改了要重启宿主，并更新 MCP 创作连接。',
  'port-edit': '修改宿主端口',
  'port-lock': '锁定宿主端口',
  'port-open-panel': '在浏览器打开',
  'port-panel-url': '面板',
  'port-mcp-url': 'MCP 创作',
  save: '保存',
  saving: '保存中…',
  saved: '已保存',
  probe: '探测',
  'restart-required': '需要重启宿主。新端口或新运行时要等宿主下次启动才接上。',
  'restart-mcp-hint': '重启后请到「智能体」更新 MCP 创作工具连接，让助手用上新端口。',
  'restart-runtime-hint': '小程序会继续用旧运行时，直到宿主重启。',
  'restart-runtime-pending': '请先保存，再重启宿主。在此之前小程序仍用旧运行时。',
  'restart-host': '重启宿主',
  'restart-wait': '正在重启宿主…',
  'restart-failed': '宿主没能重启。',
  dismiss: '关闭',
  'follow-host': '跟随宿主',
  'app-file': '应用文件',
  'clear-pin': '清除',
  refresh: '刷新',
  reload: '重新加载',
  'settings-close': '关闭设置',
  'section-appearance': '外观',
  'section-workbench': '工作台',
  'desk-switch': '工作台',
  'workbench-builtin': '小程序库',
  'workbench-mark': '工作台',
  'set-default-workbench': '设为首页',
  'current-default-workbench': '当前首页',
  'clear-default-workbench': '取消首页',
  'open-workbench-tab': '在标签中打开',
  'open-workbench-tab-now': '当前为自定义首页',
  'open-workbench-tab-more': '更多个性化设置',
  'open-workbench-tab-hint': '在独立标签中打开此工作台，可查看存储、历史和主题',
  'section-network': '网络',
  'section-runtime': '运行时',
  'section-model': '小程序模型',
  'section-agent': '智能体',
  'section-about': '关于',
  'section-mcp': 'MCP',
  'section-credentials': '凭据',
  'credentials-empty': '还没有凭据。添加一个，服务器配置里就不用直接写密钥了。',
  'credentials-add': '添加凭据',
  'credentials-new': '新建凭据',
  'credentials-edit': '编辑凭据',
  'credentials-name': '名称',
  'credentials-name-hint': '例如 github',
  'credentials-description': '描述',
  'credentials-desc-hint': '这个账号是做什么的',
  'credentials-secret': '密钥',
  'credentials-secret-hint': '粘贴 token',
  'credentials-replace-hint': '密钥留空表示不改动已保存的那个。',
  'credentials-need-name': '先给凭据起个名字。',
  'credentials-need-secret': '新建凭据必须填密钥。',
  'credentials-save': '保存',
  'credentials-saved': '只保存在这台机器上。',
  'credentials-saved-description': '描述已保存，已存的密钥没有改动。',
  'credentials-read-only': '这个存储不能在这里写入。',
  'credentials-load-failed': '读取凭据失败。',
  'credentials-save-failed': '凭据没有保存。',
  'credentials-delete-confirm': '删除这个凭据？引用它的服务器将无法启动。',
  'credentials-reference': '服务器通过 {reference} 引用它',
  'mcp-reference-hint': '值可以写成 ${env:NAME} 或 ${credential:NAME}',
  'mcp-unstarted': '未启动',
  'mcp-unresolved-hint': '下面有服务器没起来：某个值指向的东西不存在。到「凭据」里补上，然后重启宿主。',
  'mcp-add': '添加服务器',
  'mcp-new': '新建服务器',
  'mcp-edit': '编辑服务器',
  'mcp-check': '试连接',
  'mcp-check-ok': '已连接，{n} 个工具。',
  'mcp-need-name': '先填名称。',
  'mcp-save': '添加',
  'mcp-empty': '还没有服务器。添加一台，应用才能调用外部工具。',
  'mcp-transport': '传输',
  'mcp-stdio': '本地命令',
  'mcp-sse': 'SSE',
  'mcp-http': 'HTTP',
  'mcp-name': '名称',
  'mcp-description': '说明',
  'mcp-command': '命令',
  'mcp-args': '参数',
  'mcp-url': '地址',
  'mcp-env': '环境变量',
  'mcp-tools': '工具',
  'mcp-connected': '已连接',
  'mcp-offline': '未连接',
  'mcp-saved': '已保存。应用在宿主下次启动后使用这份文件。',
  'mcp-name-hint': '例如 filesystem',
  'mcp-desc-hint': '这台服务器做什么',
  'mcp-command-hint': '例如 npx',
  'mcp-args-hint': '-y @mcp/server',
  'mcp-url-hint': 'https://example.com/mcp',
  'mcp-env-hint': '每行一个 KEY=value',
  'mcp-headers': '请求头',
  'mcp-headers-hint': 'Authorization=Bearer 令牌',
  'mcp-authoring': '安装 MCP 创作工具',
  'mcp-authoring-help': '让 Cursor、Pi 等助手在这台机器上创建和修改小程序。',
  'mcp-authoring-generate': '生成连接配置',
  'mcp-authoring-install': '安装连接',
  'mcp-authoring-update-install': '更新连接',
  'mcp-authoring-failed': '连接没能装上。',
  'mcp-authoring-blurb': '在这台机器上创建和修改小程序。',
  'agent-apps-help': '小程序里的对话和代理会用这一套模型。',
  'agent-others': '对接App创作智能体',
  'agent-others-help': '给智能体安装写作技能和工具。',
  installing: '安装中',
  'skill-help': '教助手怎么写小程序。选择要装到哪些助手。',
  'skill-install': '安装写作技能',
  'skill-installed': '已安装',
  'skill-update': '可更新',
  'skill-update-install': '更新写作技能',
  'skill-version': '版本 {n}',
  'skill-reinstall': '重新安装',
  'skill-failed': '技能没能装上。',
  'skill-missing-home': '未检测到',
  'skill-open': '打开',
  'skill-custom': '自定义目录',
  'skill-custom-hint': '例如 ~/.agents/skills 或 项目/.agents/skills',
  'skill-custom-format': '最后一层目录必须叫 skills。',
  'skill-add-dir': '添加',
  'mcp-copy': '复制',
  'mcp-copied': '已复制',
  'mcp-paste': '粘贴配置',
  'mcp-from-pi': '从 Pi 导入',
  'mcp-from-file': '选择文件',
  'mcp-import': '导入',
  'mcp-admit': '识别',
  'mcp-import-none': '这份配置里没有读到服务器。',
  'mcp-load-failed': 'MCP 配置读不出来。',
  'mcp-running': '运行中',
  'mcp-stopped': '已停止',
  'mcp-more': '还有 {n}',
  'mcp-tool-empty': '这个工具没有说明。',
  'mcp-pick': '选择要导入的服务器',
  'model-empty': '当前运行时没有模型列表。',
  'runtime-missing': '没有已注册的运行时。',
  'update-checking': '正在检查…',
  'update-ok': '已是最新版本。',
  'update-available': '有新版本。',
  'update-current': '当前 {n}',
  'update-newest': '最新 {n}',
  'lang-zh': '中文',
  'lang-en': 'English',
  'theme-system': '跟随系统',
  'theme-light': '浅色',
  'theme-dark': '深色',
  'scope-global': '全局',
  'scope-app': '当前应用',
  'chip-system': '系统',
  'chip-custom': '自定义',
  'chip-app': '应用',
  'follow-global': '跟随全局',
  trash: '回收站',
  'close-panel': '关闭面板',
  appearance: '外观',
  'theme-app-hint': '可为当前小程序固定一套色板，不随宿主全局色板改动。浅色/深色仍跟随宿主。',
  palette: '配色',
  provider: '运行时',
  model: '模型',
  about: '关于',
  'product-name': '墨猴',
  'product-meaning': '墨猴是旧时帮人磨墨的小猴。它小，在手边，专门伺候一件事。\n本产品是交给用户的一套工具。用户给出想法，语言模型负责实现，墨猴提供笔墨纸砚、藏书阁和书架。',
  update: '检查更新',
  'update-install': '安装更新',
  'update-install-confirm': '安装 {n} 并重启宿主？',
  'update-installing': '正在安装更新，宿主会重启。',
  'update-install-failed': '更新没能装上。',
  settings: '设置',
  history: '历史',
  storage: '存储',
  theme: '主题',
  'pane-close': '关闭',
  'history-pick': '选择一条记录查看改动',
  'storage-empty-rows': '这张表没有记录',
  'storage-preview': '预览',
  'storage-raw': '原始数据',
} as const satisfies Record<keyof typeof en, string>

export type PanelLabelKey = keyof typeof en

const tables: Record<PanelLocale, Record<PanelLabelKey, string>> = {
  en,
  'zh-CN': zhCN,
}

/**
 * Look up one panel chrome string. A missing key fails in development and falls back to the key in production.
 * App content is not translated here.
 * @param locale - `en` or `zh-CN`
 * @param key - chrome key
 * @param mode - development fails closed
 */
export function panelText(locale: string, key: string, mode: PanelLabelMode): string {
  if (!isPanelLocale(locale)) throw new Error(`panel locale is not supported: ${locale}`)
  const value = tables[locale][key as PanelLabelKey]
  if (value !== undefined) return value
  if (mode === 'development') throw new Error(`missing panel label: ${key}`)
  return key
}

export function isPanelLocale(value: string): value is PanelLocale {
  return (panelLocales as readonly string[]).includes(value)
}
